Description of EM_ePar
Home > src > ModulationSpectrum > auxiliar_functions > EM_ePar.m
EM_ePar
PURPOSE
Generates the MS features as detailed in refs [1] and [2] using the MS
SYNOPSIS
function [ mFeatures, caFeatureNames ] = EM_ePar(ePar, vSignal, sTipo, iSubMod, eOptions, iVerbosity)
DESCRIPTION
 Generates the MS features as detailed in refs [1] and [2] using the MS
 already calculated.
 INPUTS:
       ePar - Structure containing modulation spectrum in the frames of a
       signal (vSignal) calculated with the function EM.m
       vSignal - vector containing the input signal (mono)
       iFs - The sampling rate of vSignal, in Hz.
       sTipo    any sensible combination of the following:
               'R'  rectangular window in time domain
               'N'  Hanning window in time domain
               'M'  Hamming window in time domain (default)
               't'  triangular shaped filters in mel domain (default)
               'n'  hanning shaped filters in mel domain
               'm'  hamming shaped filters in mel domain
               'C' calculate Modulation Spectra Centroids
               'Y' calculate Modulation Spectra Dynamic Range for every
                   Modulation Frequency Band
               'f' normalize Centroids respect to pitch
               'F' normalize Centroids respect to the 0Hz centroid
               'O' calculate "Low Modulation Ratio" in Modulation Spectra.
               'P' calculate Contrast, and homogeneity in Modulation Spectra modulus
                   and phase
               'A' Calculate Modulation Spectra Histogram features.
        iSubMod - Number of centroids
        eOptions - Structure containing other auxiliar and secondary
        inputs, such as:
               - iFmodMax - maximum modulation frequency
               - vFlmr - max frequency used in LMR calculation
               - EMiSubbands - desired number of acoustic subbands
               - EMsSpecopt - desired number of modulation bands
               - EMvFlmr - High bound of the band used to calculate LMR
               (25 Hz by default)
        iVerbosity - if iVerbosity==1, the function displays texts related
        to the calculation process in screen
 OUTPUTS:
       mFeatures - Matrix containing the MS features. Each row will
       be referred to a frame and, depending on the values of sTipo,
       will contain the features:
       [Centroids, Dynamic range, LMR, Modulus contrast, Modulus homogeneity,
           Phase contrast, Phase homogeneity, CIL, PALA, RALA, RALP25,
           RALP75, Ralp95]
       caFeatureNames - Includes the names of the features calculated. Has
       the same length as the number of columns of mFeatures.
 REFERENCES:
 [1] Moro-Velázquez, L., Gómez-García, J. A., Godino-Llorente, J. I., &
 Andrade-Miranda, G. (2015). Modulation spectra morphological parameters:
 a new method to assess voice pathologies according to the grbas scale.
 BioMed research international, 2015.
 [2] Moro-Velázquez, L., Gómez-García, J. A., & Godino-Llorente, J. I.
 (2016). Voice pathology detection using modulation spectrum-optimized
 metrics. Frontiers in bioengineering and biotechnology, 4, 1.
CROSS-REFERENCE INFORMATION
This function calls:
enframing_avca Function which performs framing and windowing. It permits to extract
band_reduction [ vmMS_out ] = band_reduction(vmMS_in, iNBand)
contrast_ms function [mContraste]=contrast_ms(mInput)
dynamic_range_MS function [vDR]=dynamic_range_MS(vModSpectra)
histoParamEM [mParamHist]=histoParamEM(vmMS)
homogen_ms Gray-level homogeneity in the mInput image calculated using the Bhanu
sintonizaEM Limits Modulation Spectra (vmMS) to the specified modulation (iFmodMax)
PitchKas Calculate pitch using the Kasuya pitch determination algorithm
This function is called by:
MS_features Generates the Modulation Spectra (MS) of an input signal and its