Description of histoParamEM
Home > src > ModulationSpectrum > auxiliar_functions > histoParamEM.m
histoParamEM
PURPOSE
[mParamHist]=histoParamEM(vmMS)
SYNOPSIS
function [mParamHist]=histoParamEM(vmMS, bTuned, vMf, vAf)
DESCRIPTION
 [mParamHist]=histoParamEM(vmMS)
 Calculates new parameters starting from Modulation Spectra of an audio
 sequence.
   INPUTS:
           - vmMS: Matrix vector containing Modulation Spectra
   OUTPUTS:
           - mParamHist: matrix containing in each row histogram-based
           parameters in the following order:
                   Cummulative intersection-level (CIL)
                   Number of points above linear average (PALA)
                   Ratio of points above linear average (RALA)
                   RALP25, RALP75, RALP95: Ratio of points above
                   percentiles (25, 75 and 95)
CROSS-REFERENCE INFORMATION
This function calls:
intersectcurves Intersection point for cumulative curves
sintonizaEM Limits Modulation Spectra (vmMS) to the specified modulation (iFmodMax)
This function is called by:
EM_ePar Generates the MS features as detailed in refs [1] and [2] using the MS