Description of ParamPitch
Home > src > PerturbationFluctuation > Jitter_Shimmer > ParamPitch.m
ParamPitch
PURPOSE
Calculates the pitch period and pitch amplitude sequences of the input voice
SYNOPSIS
function [vPPS, vPAS, vPitchCont, vAmpCont]=ParamPitch(vSignal, iFs, iInicio, iFinal, lMetodo)
DESCRIPTION
 Calculates the pitch period and pitch amplitude sequences of the input voice
 Input parameters:
 "vSignal":     is a column vector containing the complete speech signal
 "iFs":         is the sample rate
 "iInicio":     is the first sample of the section to be analyzed
 "iFinal":      is the last sample of the section to be analyzed
 "iNumPuntos":  is the number of HNR values ​​that are returned
 "Method":      is the analysis method to be used: 0 (Boyanov), 1 (Kasuya).
 Output parameters:
 "vPPS":       sequence of signal pitch periods (cycle by cycle).
 "vPAS":       sequence of amplitudes of the peaks of the signal cycles.
               (pitch amplitudes)
 "vPitchCont": sequence "contour of the pitch period" (of the same duration
               that the section analyzed; the period in seconds of each cycle
               of voice is repeated for all samples of the cycle)
 "vAmpCont":   sequence "contour of pitch amplitudes" (of the same duration
               that the section analyzed; the amplitude of the peak of each cycle
               of voice is repeated for all samples of the cycle)
CROSS-REFERENCE INFORMATION
This function calls:
PicosMayores Calculate the highest energy peaks, cycle by cycle of the input voice
This function is called by:
JitterShimmer Calculation of the perturbation and fluctuation parameters
Tremor Calculates the tremor (parameters that modulate the pitch period and