Description of pq
Home > src > PerturbationFluctuation > Jitter_Shimmer > pq.m
pq
PURPOSE
Calculates the disturbance ratio as a percentage of the signal vSequence,
SYNOPSIS
function iPertQuot=pq(vSecuencia, iFactorProm)
DESCRIPTION
 Calculates the disturbance ratio as a percentage of the signal vSequence,
 which can be a sequence of pitch values or peak amplitudes for example.
 Using the formula given by Kasuya.
 Input parameters:
   vInput:       input sequence
   iFactorProm:  is the averaging factor (must be odd).
 Output parameters:
   iPertQuot:    disturbance ratio as a percentage of the signal
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
apq Calculates the amplitude perturbation quotient % (APQ).
ppq Calculates the pitch perturbation quotient in % (PPQ).
rap Calculates the relative average disturbance of the pitch period in % (RAP).
sapq Calculates the smoothed amplitude perturbation quotient in % (sAPQ)
sppq Calculates the smoothed pitch perturbation quotient in % (sPPQ)