Description of SecuenPitch
Home > src > PerturbationFluctuation > Jitter_Shimmer > SecuenPitch.m
SecuenPitch
PURPOSE
Calculates the pitch or amplitude sequences given a vSignal
SYNOPSIS
function [vPPS, vPAs, vPitchCont, vAmpCont]=SecuenPitch(vSignal, iFs, iInicio, iFinal, iMetodo)
DESCRIPTION
 Calculates the pitch or amplitude sequences given a vSignal
 Input parameters:
     vSignal: column vector containing the full speech signal
     iFs:     the sampling frequency
     i:     Start the first sample of the section to be analyzed
     iFinal:     the last sample of the section to be analyzed
     iNumPuntos:     number of HNR values ​​returned
     lMetodo:    analysis to be used: 0 (Boyanov), 1 (Kasuya).
 Output parameters:
     vPPS sequence of pitch periods (cycle to cycle).
     vPAS sequence of peak amplitudes of signal cycles. (pitch amplitudes)
     vPitchCont sequence "contour of the pitch period" (of the same duration
             that the analyzed section; the period in seconds of each cycle
             of voice is repeated for all samples of the cycle)
     vAmpCont sequence "contour of pitch amplitudes" (of the same duration
             that the analyzed section; the amplitude of the peak of each cycle
             of voice is repeated for all samples of the cycle)
CROSS-REFERENCE INFORMATION
This function calls:
QuitaExtremos This function removes the 0's (or low amplitude values) at the beginning or at the end
PicosNeg Obtains the amplitudes P and the positions i_P of the negative peaks,
PicosNegKas Computes the amplitudes P and the positions i_P of the negative peaks,
PicosPos Gets the amplitudes P and the i_P positions of the positive peaks,
PicosPosKas Computes the amplitudes P and the positions i_P of the positive peaks,
PitchKas Calculate pitch using the Kasuya pitch determination algorithm
This function is called by: