clear variables
close all
clc

addpath(genpath('./External Toolboxes/m2html/'))

m2html('mfiles','./src',...
    'htmldir', 'doc',...
    'recursive', 'on',...
    'graph', 'on',...
    'source', 'off',...
    'global','on' );