Description of PicosMayores
Home > src > PitchDetermination > boyanov > PicosMayores.m
PicosMayores
PURPOSE
Calculate the highest energy peaks, cycle by cycle of the input voice
SYNOPSIS
function [vAmax, vPosAmax, mPicosPos]=PicosMayores(vSignal, iFs, iInicio, iFinal, lMetodo)
DESCRIPTION
 Calculate the highest energy peaks, cycle by cycle of the input voice
 Input parameters
   vSignal:       is a column vector containing the complete speech signal
   iFs:           is the sampling frequency
   iInicio:       is the first sample of the section to be analyzed
   iFinal:        is the last sample of the section to be analyzed
   lMethod:       indicates the method to be used:
                   lMethod = 0: Boyanov
                   lMethod = 1: Kasuya
 Output parameters
   vAmax:         amplitudes of the highest energy peaks, cycle by cycle, of a speech frame;
   vPosAmax:      positions of the highest energy peaks, cycle by cycle, of a voice frame;
   mPicosPos:     Peak signal (of the same duration as vSignal) with the peaks found.
CROSS-REFERENCE INFORMATION
This function calls:
QuitaExtremos This function removes the 0's (or low amplitude values) at the beginning or at the end
Picos Computes the amplitudes P and the i_P positions of the positive or negative peaks
PitchBoy Calculate the pitch following Boyanov's recommendations.
PicosKas Computes the amplitudes P and the i_P positions of the positive or negative peaks
PitchKas Calculate pitch using the Kasuya pitch determination algorithm
This function is called by:
ParamPitch Calculates the pitch period and pitch amplitude sequences of the input voice
HNRYum Calculates the harmonic ratio to HNR noise in dB according to the Yumoto method