Description of PitchBoyanov
Home > src > PitchDetermination > boyanov > PitchBoyanov.m
PitchBoyanov
PURPOSE
Calculates the pitch of a given frame using the method described in:
SYNOPSIS
function iFo = PitchBoyanov(vFrame, iFs, iT0)
DESCRIPTION
 Calculates the pitch of a given frame using the method described in:
 B. Boyanov, S. Hadjitodorov, B. Teston, D. Doskov. Robust hybrid pitch
 detector for pathologic voice analysis. Larynx 97, Jun 1997, Marseille, France. pp.55-58.
 According to the temporal and cesptral method
 Inputs:
   vFrame               = Input vFrame
   iFs                  = Sampling frequency
   iT0                  = Previous calculation of the pitch period
 Outputs:
   vFo                  = Pitch value of the current frame
CROSS-REFERENCE INFORMATION
This function calls:
SilentDetectorThreshold Calculates if the vFrame is silent or not according to the energy of
DynamicClip Dynamic central clipping with threshold adaptation
PitchDetecBoy Calculates the pitch using the Boyanov algorithm
This function is called by:
NNE Calculates the normalized noise energy (NNE) of a speech segment (according to
CalculatePitch Calculates the pitch of a given frame using different pitch
PitchBoy Calculate the pitch following Boyanov's recommendations.