Description of PitchKas
Home > src > PitchDetermination > kasuya_feijoo > PitchKas.m
PitchKas
PURPOSE
Calculate pitch using the Kasuya pitch determination algorithm
SYNOPSIS
function T=PitchKas(vSignal, iFs, iInicio, iFinal)
DESCRIPTION
 Calculate pitch using the Kasuya pitch determination algorithm
 Input parameters
   vSignal: vector column containing the complete speech signal
   iFs:     the sampling frequency
   iInicio: Staring sample of the section to be analyzed
   iFinal:  the last sample of the section to be analyzed
 Output parameters
   T:       the sequence of pitch period values (in samples) calculated on
            segments of 40ms, with displacements of 20ms, as Kasuya and Feijoo do.
CROSS-REFERENCE INFORMATION
This function calls:
PitchSegKas Calculates the pitch of a given frame using the method described by
This function is called by:
EM_ePar Generates the MS features as detailed in refs [1] and [2] using the MS
SecuenPitch Calculates the pitch or amplitude sequences given a vSignal
PicosMayores Calculate the highest energy peaks, cycle by cycle of the input voice
PitchMedio Calculates the average pitch in Hz of the input voice