Description of PitchMedio
Home > src > PitchDetermination > kasuya_feijoo > PitchMedio.m
PitchMedio
PURPOSE
Calculates the average pitch in Hz of the input voice
SYNOPSIS
function [rFo, vF0]=PitchMedio(vSignal, iFs, iInicio, iFinal)
DESCRIPTION
 Calculates the average pitch in Hz of the input voice
 The average pitch period is calculated for the voice section under analysis
 using the Kasuya procedure (40ms windows with 50% overlap)
 Input parameters
   vSignal:    vector column containing the complete speech signal
   iFs:        the sampling frequency
   i:          Starting sample of the section to be analyzed
   iFinal:     The last sample of the section to be analyzed
 Output parameters
   rFo:        average pitch calculated over 40ms segments,
               with displacements of 20ms, as Kasuya and Feijoo do.
CROSS-REFERENCE INFORMATION
This function calls:
PitchKas Calculate pitch using the Kasuya pitch determination algorithm
This function is called by:
CHNR Calculates the harmonic-to-noise ratio (HNR) of a voice signal, using
CHNRKrom Calculates the harmonic-to-noise ratio (HNR) of a voice signal, using
NNE Calculates the normalized noise energy (NNE) of a speech segment (according to
NNEs Calculates the normalized noise energy (NNE) of a voice signal,