Description of PitchSegKas
Home > src > PitchDetermination > kasuya_feijoo > PitchSegKas.m
PitchSegKas
PURPOSE
Calculates the pitch of a given frame using the method described by
SYNOPSIS
function vT0 = PitchSegKas(vFrame, iFs)
DESCRIPTION
 Calculates the pitch of a given frame using the method described by
 Kasuya in:
       Kasuya, H., Ogawa, S., Kikuchi, Y., & Ebihara, S. (1986). An
       acoustic analysis of pathological voice and its application to the
       evaluation of laryngeal pathology. Speech communication, 5(2), 171-181.
 Inputs:
   vFrame               = Input vFrame
   iFs                  = Sampling frequency
 Outputs:
   vFo                  = Column vector of size 1,2 or 3, considering the
                          possible pitch candidates of the frame according
                          to the algorithm of Kasuya (candidates are ordered)
CROSS-REFERENCE INFORMATION
This function calls:
SilentDetectorThreshold Calculates if the vFrame is silent or not according to the energy of
This function is called by:
CalculatePitch Calculates the pitch of a given frame using different pitch
PitchKas Calculate pitch using the Kasuya pitch determination algorithm