Description of HNRYum
Home > src > PerturbationFluctuation > Perturbation > HNR > HNRYum.m
HNRYum
PURPOSE
Calculates the harmonic ratio to HNR noise in dB according to the Yumoto method
SYNOPSIS
function [vHNR, rHNR]=HNRYum(vSignal, iFs, iInicio, iFinal, iNumPuntos)
DESCRIPTION
 Calculates the harmonic ratio to HNR noise in dB according to the Yumoto method
   Yumoto, E., Gould, W. J., & Baer, T. (1982). Harmonics‐to‐noise ratio
   as an index of the degree of hoarseness. The journal of the Acoustical
   Society of America, 71(6), 1544-1550.
   Yumoto, E., Sasaki, Y., & Okamura, H. (1984). Harmonics-to-noise ratio
   and psychophysical measurement of the degree of hoarseness. Journal of
   Speech, Language, and Hearing Research, 27(1), 2-6.
 Input parameters
   vSignal:    Column vector containing the complete speech signal
   iFs:        the sampling rate
   iInicio:    Start the first sample of the section to be analyzed
   iFinal:     the last sample of the section to be analyzed
   iNumPoints: the number of HNR values returned
 Output parameters
   vHNR:     Row vector of dimension "iNumPuntos" that contains the
             instantaneous values of the HNR
   rHNR:     the average value of the HNR
CROSS-REFERENCE INFORMATION
This function calls:
SeparaCiclos Separates the cycles of a known voice signal given the moments in which
HNRiYumBoy Calculates the value of the HNR ratio for a speech segment corresponding to
PicosMayores Calculate the highest energy peaks, cycle by cycle of the input voice
This function is called by:
AdditiveNoise Calculation of the additive noise parameters