Description of GNE
Home > src > PerturbationFluctuation > Perturbation > GNE > GNE.m
GNE
PURPOSE
Calculates the GNE -Glottal-to-Noise Excitation ratio- according to
SYNOPSIS
function [vGNEValues, rGNEFactor]=GNE(vSignal, iFs, iInicio, iFinal,iNumFrames, rFrameSize, iBW, iFShift)
DESCRIPTION
 Calculates the GNE -Glottal-to-Noise Excitation ratio- according to
 the Michaelis algorithm [1]. The signal is resampled at 10 kHz,
 obtains the glottal waveform by reverse filtering and is divided into
 temporary windows. From each window the correlation between the
 Hilbert envelopes of different frequency bands is computed, being the GNE
 the maximum value.
 [1] D. Michaelis, T. Gramss and H. W. Strube, "Glottal-to-Noise Excitation
 ratio - a new measure for describing pathological voices ", Acustica / Acta
 Acoustic%, vol. 83, pp. 700-706, 1997.
 Input parameters:
       vSenal: Vector that contains the samples of the voice signal whose
               GNE is to be calculated.
       iFs: Original sampling rate of the voice signal.
       iStart: first sample of the section to be analyzed.
       iFinal: last sample of the section to be analyzed.
       iNumPtos: Number of temporary windows into which the signal is divided.
               Indicates the number of calculated GNE values​ for each signal
               voice. Must be a positive integer and sufficient to cover the
               entire signal.
       rFrameSize: Duration (in ms) of each analysis window.
       iBW:    Bandwidth (Hz) of the frequency bands.
               Recommended: 1000, 2000, 3000 Hz.
       iFShift: Displacement (Hz) between the center frequencies of the
               frequency bands. Recommended: 100, 200, 300 Hz.
 Output parameters:
       vValoresGNE: row vector of length iNumPtos that stores the GNEs of
           each time window.
       rFactorGNE: Average value of the GNE parameter of the voice signal.
CROSS-REFERENCE INFORMATION
This function calls:
CalculaEnvolventesHilbert Calculates the Hilbert envelopes in different frequency bands of each of the input voice
CalculaParesHilbert Calculates the center frequencies for which the cross correlations of Hilbert envelopes are to be computed.
EstructuraFina Calculate the fine structure or the glottic excitation signal (FineStructure)
This function is called by:
AdditiveNoise Calculation of the additive noise parameters