Description of LogEnergy
Home > src > Aux > LogEnergy.m
LogEnergy
PURPOSE
Calculates the energy of a frame in logarithmic and linear scale,
SYNOPSIS
function [rElog, rE] = LogEnergy(vFrame)
DESCRIPTION
 Calculates the energy of a frame in logarithmic and linear scale,
 normalized by the number of samples
 Inputs:
   vFrame     = Input vFrame
 Outputs:
   rElog      = Energy in logarithmic scale
   rE         = Energy in linear scale.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
ErrorPredNorm Normalized Prediction error in dB
SilentDetectorThreshold Calculates if the vFrame is silent or not according to the energy of
PLPi Calculates the Perceptual linear prediction coefficients of a single frame