Description of QuitaExtremos
Home > src > Aux > QuitaExtremos.m
QuitaExtremos
PURPOSE
This function removes the 0's (or low amplitude values) at the beginning or at the end
SYNOPSIS
function vSignalRecortada=QuitaExtremos(vSignal, iUmbral)
DESCRIPTION
 This function removes the 0's (or low amplitude values ) at the beginning or at the end
 of the signal, vSignal, if any.
 Its utility is to eliminate the null values of the windowed parameters (pitch, energy, ...)
 assigned at the beginning and end of the voice signal (when the analysis
 window is outside the boundaries of voice signal).
 Input parameters:
   vSignal: vector that contains the section of signal to analyze
 Output parameters:
   vSignal Trimmed: vector containing the trimmed signal segment
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
SecuenPitch Calculates the pitch or amplitude sequences given a vSignal
HNRiYum Calculates the value of the HNR ratio for a speech segment corresponding to
HNRiYumBoy Calculates the value of the HNR ratio for a speech segment corresponding to
PicosMayores Calculate the highest energy peaks, cycle by cycle of the input voice