Description of SilentDetectorThreshold
Home > src > Aux > SilentDetectorThreshold.m
SilentDetectorThreshold
PURPOSE
Calculates if the vFrame is silent or not according to the energy of
SYNOPSIS
function bSound = SilentDetectorThreshold(vFrame)
DESCRIPTION
 Calculates if the vFrame is silent or not according to the energy of
 the segment using thresholds
 Inputs:
   vFrame               = Input vFrame
 Outputs:
   bSound               = Boolean indicating if the frame is silent or not
CROSS-REFERENCE INFORMATION
This function calls:
AC1 Normalized autocorrelation coefficient for a lag of 1 of a vFrame
ErrorPredNorm Normalized Prediction error in dB
LPCcoef1 Calculates the first prediction coefficient considering a LPC analysis of order 12
LogEnergy Calculates the energy of a frame in logarithmic and linear scale,
ZeroCrossingRate Calculate the zero-crossing rate of the frame
This function is called by:
PitchBoyanov Calculates the pitch of a given frame using the method described in:
PitchSegKas Calculates the pitch of a given frame using the method described by