Description of NNE
Home > src > PerturbationFluctuation > Perturbation > nne > NNE.m
NNE
PURPOSE
Calculates the normalized noise energy (NNE) of a speech segment (according to
SYNOPSIS
function [vNNE, rNNEmean]=NNE(vSignal, iFs, iInicio, iFinal, iNumPuntos, iFo)
DESCRIPTION
 Calculates the normalized noise energy (NNE) of a speech segment (according to
 the Kasuya'86 method)
 Input parameters
 vSignal:  Column vector containing the full speech signal
 iFs:      Sample Rate (Hz)
 iStart:   First sample of the signal to be analyzed
 iFinal:   Last sample of the signal to be analyzed
 iNumPuntos:   Number of NNE values returned
 iFo:      Pitch frequency of the voice
 Output parameters
 rNNE:     row vecotr of dimension "iNumPuntos" that contains the
           instantaneous values of the NNE
 rNNEmean: average value of the NNE
CROSS-REFERENCE INFORMATION
This function calls:
NNEi Calculates the normalized noise energy (NNE) of a voice segment according to
PitchBoyanov Calculates the pitch of a given frame using the method described in:
PitchMedio Calculates the average pitch in Hz of the input voice
This function is called by:
AdditiveNoise Calculation of the additive noise parameters