Description of AdditiveNoise
Home > src > PerturbationFluctuation > AdditiveNoise.m
AdditiveNoise
PURPOSE
Calculation of the additive noise parameters
SYNOPSIS
function vParameters = AdditiveNoise(vSignal, iFs, iFrameSize, iOverlap)
DESCRIPTION
 Calculation of the additive noise parameters
 Inputs:
   vFrame               = Input vFrame
   iFs                  = Sampling frequency
   iFrameSize           = Number of samples used to define the frame of
                          analysis
   iOverlap             = Number of samples for ovelapping windows
 Outputs:
   vParameters          = Vector containing the following additive noise parameters
                           - vNNE: Normalized noise energy
                           - vHNR: Harmonics to noise ratio - Yumoto
                           - vGNE: Glottal-to-noise excitation ratio
                           - vCHNR: Cespstrum harmonics-to-noise ratio
CROSS-REFERENCE INFORMATION
This function calls:
CHNR Calculates the harmonic-to-noise ratio (HNR) of a voice signal, using
GNE Calculates the GNE -Glottal-to-Noise Excitation ratio- according to
HNRYum Calculates the harmonic ratio to HNR noise in dB according to the Yumoto method
NNE Calculates the normalized noise energy (NNE) of a speech segment (according to
This function is called by: