Description of JitterShimmer
Home > src > PerturbationFluctuation > JitterShimmer.m
JitterShimmer
PURPOSE
Calculation of the perturbation and fluctuation parameters
SYNOPSIS
function [vJitter, vShimmer] = JitterShimmer(vSignal, iFs)
DESCRIPTION
 Calculation of the perturbation and fluctuation parameters
 Inputs:
   vSignal              = Input signal
   iFs                  = Sampling frequency
 Outputs:
   vJitter              = Family of parameters based on jitter. Returns a
                          vector with the following parameters:
                           rJitta:   absolute value in microseconds
                           rJitt:   relative value in % with respect to the average value of the period
                           rRrRAP = rap( vPPS );
                           rPPQ: pitch perturbation quotient in %
                           rSPPQ: smoothed pitch perturbation quotient in % (sPPQ).
   vShimmer             = Family of parameters based on shimmer. Returns a
                          vector with the following parameters:
                           rShdB:     absolute shimmer in dB
                           rShim:     relative shimmer in %
                           rAPQ:      amplitude perturbation quotient % (APQ).
                           rSAPQ:     smoothed amplitude perturbation quotient in % (sAPQ).
CROSS-REFERENCE INFORMATION
This function calls:
ParamPitch Calculates the pitch period and pitch amplitude sequences of the input voice
apq Calculates the amplitude perturbation quotient % (APQ).
jitter Calculates the jitter of the voice signal. Calculate its absolute value
ppq Calculates the pitch perturbation quotient in % (PPQ).
rap Calculates the relative average disturbance of the pitch period in % (RAP).
sapq Calculates the smoothed amplitude perturbation quotient in % (sAPQ)
shimmer Calculates the shimmer of the signal. Calculate its absolute value
sppq Calculates the smoothed pitch perturbation quotient in % (sPPQ)
This function is called by: