Description of CalculatePitch
Home > src > PitchDetermination > CalculatePitch.m
CalculatePitch
PURPOSE
Calculates the pitch of a given frame using different pitch
SYNOPSIS
function [iF0Out, vF0] = CalculatePitch(vSignal, iFs, iNumberOfFrames, sType)
DESCRIPTION
 Calculates the pitch of a given frame using different pitch
 implementations
 Inputs:
   vSignal              = Input signal
   iFs                  = Sampling frequency
   iNumberOfFrames      = desired number of frames. The overlapping is
                          varied to ensure that the number of frames is
                          achieved. The default value, iDesiredNumberOfFrames,
                          is twice the number of the frames that will result
                          if the window size was fit to 40e-3. This emulates an
                          overlap of 50%.
   sType  =    'Boyanov': Dynamic clipping in the temporal domain
               according to:
                   B. Boyanov, S. Hadjitodorov, B. Teston, D. Doskov. Robust hybrid pitch
                   detector for pathologic voice analysis. Larynx 97, Jun 1997, Marseille, France. pp.55-58.
               'Rabiner_StaticClip': Static clipping -> Signal is clipped using
                       static thresholds
               'Rabiner_LPC'
               'Rabiner_Cesptral'
               'Kasuya' according to:
                   Kasuya, H., Ogawa, S., Kikuchi, Y., & Ebihara, S. (1986).
                   An acoustic analysis of pathological voice and its application
                   to the evaluation of laryngeal pathology.
                   Speech communication, 5(2), 171-181.
 Outputs:
   vFo  = Pitch value
CROSS-REFERENCE INFORMATION
This function calls:
PitchBoyanov Calculates the pitch of a given frame using the method described in:
PitchSegKas Calculates the pitch of a given frame using the method described by
PitchCeps Pitch estimation using the LPC method of Rabiner
PitchClip Pitch estimation using static clipping
PitchCorr Pitch estimation using the LPC method of Rabiner
This function is called by: